# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.101'
- task: DotNetCoreCLI@2
  displayName: 'My Build'
  inputs:
    command: 'build'
    projects: |
      ./Tutorial 1 and 2/MyAppT/MyAppT
- task: DotNetCoreCLI@2
  displayName: 'My Test'
  inputs:
    command: 'test'
    projects: './Tutorial 1 and 2/MyAppT/TestingProject'
#    arguments: '''--configuration $(buildConfiguration) --collect "Code coverage"'''